version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
- choco install opencover.portable
- choco install codecov
build:
  verbosity: minimal
configuration:
  - Debug
  - Release
artifacts:
 - path: UnitTestDemo\bin\$(configuration)
   name: Demo
   type: zip
test_script:
 - OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test" -output:coverage.xml -register:user -filter:"+[*]* -[*Moq]* -[xunit*]*" -oldstyle
 - codecov -f "coverage.xml"

